services:
  - type: web
    name: wizzair-bot
    env: node
    buildCommand: |
      npm install
      npx playwright install chromium --with-deps
    startCommand: npm start
    envVars:
      - key: WIZZ_EMAIL
        sync: false
      - key: WIZZ_PASS
        sync: false
